#!/bin/bash
# Historically we needed to patch some files in Otto Motors' ROS 2 API, but this is no longer needed
# Intead just use this to make sure the correct version is installed

if [ -z $ROS2_DISTRO ];
then
  ROS2_DISTRO=galactic
fi

sudo apt-get install ros-$ROS2_DISTRO-clearpath-api ros-$ROS2_DISTRO-clearpath-api-examples
